import type { Metadata } from 'next';
import { Open_Sans, Lora } from 'next/font/google';
import './globals.css';
import StoryblokProvider from '@/components/storyblokProvider';
import { getStoryblokApi } from '@/lib/storyblok';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import styles from '@/app/ui/layout.module.css';

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
});

const open_sans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = await getNavigation();
  const footer = await getFooter();

  return (
    <StoryblokProvider>
      <html lang='de' className={`default-theme ${styles.page}`}>        
        <body className={`${lora.variable} ${open_sans.variable}`}>
          <Navigation blok={navigation.content.nav_items} />
          {children}
          <Footer blok={footer.content}/>
        </body>
      </html>
    </StoryblokProvider>
  );
}

export async function getNavigation() {
  const storyblokApi = getStoryblokApi();
  const { data } = await storyblokApi.get('cdn/stories/main-navigation', {
    version: 'published',
  });
  return data.story;
}

export async function getFooter() {
  const storyblokApi = getStoryblokApi();
  const { data } = await storyblokApi.get('cdn/stories/footer', {
    version: 'published',
  });
  return data.story;
}
